export * from "./LandingPage";
export * from "./hero-Section";
export * from "./skils-List";
export * from "./populerDoctors";
export * from "./prescription";
export * from "./newDr";
export * from "./Comments";
export * from "./Questions";
export * from "./Blogs";
